version: '3.8'

services:
  # 🌐 V-Closet Web API Service
  api:
    image: vcloset-api:latest
    container_name: vcloset-api-container
    build:
      context: .
      dockerfile: VCloset.API/Dockerfile
    env_file:
      - .env
    ports:
      - "5070:8080" # Map host port 5070 to container port 8080
    volumes:
      - ./uploads:/app/wwwroot/uploads
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
